package com.hewei.hzyjy.xunzhi.interview.api.io.resp;

import lombok.Data;

/**
 * 面试题回答响应DTO
 */
@Data
public class InterviewAnswerRespDTO {
    
    /**
     * 题号
     */
    private String questionNumber;
    
    /**
     * 题目内容
     */
    private String questionContent;
    
    /**
     * 本次得分
     */
    private Integer score;
    
    /**
     * 累计总分
     */
    private Integer totalScore;
    
    /**
     * 是否成功
     */
    private Boolean isSuccess;
    
    /**
     * 错误信息
     */
    private String errorMessage;
    
    /**
     * AI评价内容（可选）
     */
    private String feedback;

    /**
     * Next question content generated by backend orchestrator.
     */
    private String nextQuestion;

    /**
     * Next question number in the main-question sequence.
     */
    private String nextQuestionNumber;

    /**
     * Whether next question is a follow-up question.
     */
    private Boolean isFollowUp;

    /**
     * Current follow-up count for this main question.
     */
    private Integer followUpCount;

    /**
     * Whether interview is finished.
     */
    private Boolean finished;

    /**
     * 初始化默认响应，避免每次手动 set 基础状态。
     */
    public static InterviewAnswerRespDTO init() {
        InterviewAnswerRespDTO resp = new InterviewAnswerRespDTO();
        resp.setIsSuccess(false);
        resp.setFinished(false);
        resp.setIsFollowUp(false);
        resp.setFollowUpCount(0);
        return resp;
    }

    /**
     * 标记失败并写入错误信息。
     */
    public InterviewAnswerRespDTO fail(String errorMessage) {
        this.setErrorMessage(errorMessage);
        this.setIsSuccess(false);
        return this;
    }

    /**
     * 标记成功。
     */
    public InterviewAnswerRespDTO success() {
        this.setIsSuccess(true);
        return this;
    }

    /**
     * 写入当前作答题目的元信息。
     */
    public InterviewAnswerRespDTO withCurrentQuestion(String questionNumber, String questionContent) {
        this.setQuestionNumber(questionNumber);
        this.setQuestionContent(questionContent);
        return this;
    }

    /**
     * 写入评分与反馈信息。
     */
    public InterviewAnswerRespDTO withEvaluation(Integer score, String feedback, Integer totalScore) {
        this.setScore(score);
        this.setFeedback(feedback);
        this.setTotalScore(totalScore);
        return this;
    }

    /**
     * 写入下一题信息（可用于主问题或追问）。
     */
    public InterviewAnswerRespDTO withNextQuestion(
            String nextQuestionNumber,
            String nextQuestion,
            boolean isFollowUp,
            Integer followUpCount) {
        this.setNextQuestionNumber(nextQuestionNumber);
        this.setNextQuestion(nextQuestion);
        this.setIsFollowUp(isFollowUp);
        this.setFollowUpCount(followUpCount == null ? 0 : followUpCount);
        this.setFinished(false);
        return this;
    }

    /**
     * 标记面试结束并清理下一题字段。
     */
    public InterviewAnswerRespDTO finish() {
        this.setFinished(true);
        this.setIsFollowUp(false);
        this.setFollowUpCount(0);
        this.setNextQuestion(null);
        this.setNextQuestionNumber(null);
        return this;
    }
}
